### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by minhnimble** [akazadd/NimbleTechTest#20]
Hello Mohammad 👋 , thank you for your effort on the code submission. I am Mike, Engineering Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by akazadd** [comment]
Hello Mike,

Thank you for taking the time to review my code submission, and I
appreciate your detailed approach to the code review process. I'm excited
to work with you on addressing the identified issues and making the
necessary improvements to the codebase.

I'm completely aligned with the process you've outlined, and I understand
the importance of timely responses. Rest assured, I will be responsive
throughout the review process. If I need any clarifications or have
questions, I won't hesitate to reach out to you.

I'm grateful for the opportunity to work together on this, and I'm looking
forward to your feedback. Let's make this code the best it can be!

Best regards,
Mohammad Abul Kalam Azad

**Comment by minhnimble** [comment]
Hi, Mohammad 👋

For your information, I just complete the 1st round of review now. Please go ahead and provide your feedback on all the proposed issues. Regarding the timeline, please note that the target is to conclude everything by the end of next Monday, thus it would be best if you could address the issues before that time. If you have any further inquiry, please don't hesitate to communicate them here.

Have a great day!

**Comment by akazadd** [comment]
Hello! 👋

Thank you for completing the 1st round of review and for the update. I
appreciate your prompt feedback. I will start addressing the proposed
issues right away and will ensure that all necessary improvements are made
before the end of next Monday.

If I have any questions or need further clarification while addressing the
issues, I will not hesitate to reach out to you here.

Wishing you a great day too!

Best regards,
Abul Kalam Azad

**Comment by akazadd** [comment]
Hi Mike! 👋

I'm pleased to inform you that I've addressed all the proposed issues from the code review. The updated codebase is available on the Git repository, and I've created a pull request for each issue, providing a clear view of the changes made.

Feel free to review the pull requests at your convenience, and check if everything meets the expectations,.

Thank you for your guidance throughout this process, and I appreciate your time and feedback.

Best regards,
Mohammad Abul Kalam Azad

**Comment by minhnimble** [comment]
Good morning @akazadd  ☀️

As of this point, this code challenge review session has concluded, and no further discussion will be needed from your end. About the next step, you will hear from the Talent Acquisition team about the decision as soon as possible. 🙏

Ultimately, it was a pleasure reviewing your code and getting to know you. Thanks for your time and I wish you all the best! 🍀
