### ISSUE TITLE
[Feature] Pagination support

### ISSUE THREAD

**Issue by minhnimble** [akazadd/NimbleTechTest#21]
## Issue

As you can probably see from the Postman, the  `Surveys List API` should be capable of providing more data than what the application currently displays. Currently, the data shown on the Surveys List screen is only fixed to a page of 5 items. As a result, there is no way for the user to see all the data available from the API response.

https://github.com/akazadd/NimbleTechTest/blob/e6c67511d586c9707b45295fd5591ffb1b57a474/NimbleTechTest/Home/HomeViewController.swift#L43

## Expect

The application could paginate to load all the survey list data by using some user inputs (swipe to the last survey item to trigger the load more action, add the load next page button, etc.).

**Comment by akazadd** [comment]
Hello Mike,

Thank you for pointing out the limitation in the current Surveys List API
implementation. I understand the requirement, and I will work on enhancing
the functionality to allow users to paginate and load all survey data based
on your suggestions.

I'll explore options such as implementing infinite scrolling (where new
data is loaded as the user scrolls to the end of the list), adding a "Load
More" button, or incorporating swipe-to-load functionality. I will
carefully evaluate these options and choose the one that best fits the user
experience and the application's design.

I'll keep you updated on my progress and let you know once the enhancements
are implemented. If you have any specific preferences or additional
suggestions regarding the implementation, please feel free to share them.

Thank you for your guidance, and I'm committed to making the necessary
improvements to meet the expectations.

Regards,
Mohammad Abul Kalam Azad

**Comment by akazadd** [comment]
Pull Request -> https://github.com/akazadd/NimbleTechTest/pull/35
