### ISSUE TITLE
[Bug] Stuck at a gray screen or crash the application when there is an error from the API on Login page

### ISSUE THREAD

**Issue by minhnimble** [akazadd/NimbleTechTest#25]
## Issue

When the user provides an invalid combination of email and password, there is no handling or a visible prompt on the application to let the user know what is currently happening. Instead, the application just show a gray screen and stuck there forever.

When attempting to log in to the application without any connection, it actually crashes the app.

## Expect

Error cases should be visibly handled on the application and let the user know what is happening.

## Steps to reproduce

- Provide an invalid combination of email and password:

https://github.com/akazadd/NimbleTechTest/assets/70877098/bef3a8ea-6be5-4ac4-8845-908227a675df

- Log in to the application without any connection:

https://github.com/akazadd/NimbleTechTest/assets/70877098/9bbdbbdd-f2e1-4743-9277-f5d647b23182

**Comment by akazadd** [comment]
Pull Request -> https://github.com/akazadd/NimbleTechTest/pull/34
