### ISSUE TITLE
[Bug] Some test cases are failing

### ISSUE THREAD

**Issue by minhnimble** [akazadd/NimbleTechTest#26]
## Issue

It is quite nice to see that you've included a few unit tests for multiple View Models of the application. Unfortunately, there is a run test failed issue when I attempted to run them on my Simulator iPhone 15 iOS 17.0.1 with the latest code at the commit e6c67511d586c9707b45295fd5591ffb1b57a474.

Here is the screenshot about the error issue:

![Screenshot 2023-11-09 at 15 19 50](https://github.com/akazadd/NimbleTechTest/assets/70877098/e8fbcb65-1403-45c7-bff8-c5dfc3b4055b)

## Expect

All tests should run successfully without any issue.

## Step to reproduce

1. Run `pod install` to set up the project environments.
2. Open the project with the `.xcworkspace` file.
3. Run debug on the project successfully with `Cmd + R`.
4. Run test on the project with `Cmd + U`.
5. Observe the result.

**Comment by akazadd** [comment]
Pull Request -> https://github.com/akazadd/NimbleTechTest/pull/36
